Training:
  embedding_max_len: 512
  model: pretrained
  batch_size: 3
  num_workers: 0
  shuffle: True
  epochs: 10


Inference:
  embedding_max_len: 512
  model: pretrained
  batch_size: 25
  num_workers: 0
  shuffle: True
