Training:
  embedding_max_len: 512
  model: finetuned
  batch_size: 10
  num_workers: 0
  shuffle: True
  epochs: 8


Inference:
  embedding_max_len: 512
  model: pretrained
  batch_size: 25
  num_workers: 0
  shuffle: True
